name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Ninja
        run: sudo apt install -y g++ cmake ccache ninja-build checkinstall

      - name: Build And Run
        run: sudo bash ${{github.workspace}}/package_and_run.sh