name: C/C++ CI

on: [push]

jobs:
  ubuntu-build-with-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build And Run
        run: sudo bash ${{github.workspace}}/package_and_run.sh